version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - suitcase-network
        volumes:
            - redis-data:/data
        restart: always

    api:
        build:
            context: ../api
            dockerfile: Dockerfile
        container_name: suitcase-api
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379
        ports:
            - '3001:3001'
        networks:
            - suitcase-network
        restart: always

    engine:
        build:
            context: ../engine
            dockerfile: Dockerfile
        container_name: suitcase-engine
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379
        networks:
            - suitcase-network
        restart: always
        volumes:
            - engine-data:/app/data

    websocket:
        build:
            context: ../websocket
            dockerfile: Dockerfile
        container_name: suitcase-websocket
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis://redis:6379
        ports:
            - '3003:3003'
        networks:
            - suitcase-network
        restart: always

networks:
    suitcase-network:
        driver: bridge

volumes:
    redis-data:
    engine-data:
